"""
Blender script: create bones whose endpoints are placed at selected mesh faces.

Usage:
- Open the mesh in Edit Mode and select faces you want to rig.
- Have an Armature object selected too (or none to create a new one).
- Run this script from Blender's Text Editor or command line.

What it does:
- For each selected face it creates an EditBone where the head is at the face centroid
  (in armature local space) and the tail is offset along the face normal.
- Creates a vertex group per bone and assigns the face's vertices with weight=1.0.
- Adds an Armature modifier to the mesh (if missing) and targets the armature.

Notes / safety:
- Run from the same Blender file that contains the mesh and (optionally) armature.
- This script expects Blender 2.80+ API (`bpy`).

Author: generated by assistant
"""

import bpy
import bmesh
from mathutils import Vector
import math


def ensure_armature(selected_armature_name=None):
    # If an armature is selected, use it. Otherwise create a new armature object.
    arm_obj = None
    for obj in bpy.context.selected_objects:
        if obj.type == 'ARMATURE':
            arm_obj = obj
            break
    if arm_obj is None and selected_armature_name:
        arm_obj = bpy.data.objects.get(selected_armature_name)
    if arm_obj is None:
        # create a new armature
        arm_data = bpy.data.armatures.new('AutoRigArmature')
        arm_obj = bpy.data.objects.new('AutoRigArmature', arm_data)
        bpy.context.collection.objects.link(arm_obj)
    return arm_obj


def get_selected_mesh_object():
    obj = bpy.context.view_layer.objects.active
    if obj and obj.type == 'MESH':
        return obj
    # fallback: find any selected mesh
    for o in bpy.context.selected_objects:
        if o.type == 'MESH':
            return o
    return None


def main(bone_length_factor=0.2, bone_name_prefix='face'):
    mesh_obj = get_selected_mesh_object()
    if mesh_obj is None:
        print('No mesh object selected/active. Select a mesh and run again.')
        return

    # Ensure we are in Object mode to access mesh data safely
    prev_mode = bpy.context.mode
    if prev_mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')

    # get bmesh of mesh (read edit-mode selection if necessary)
    bm = None
    in_edit = False
    if mesh_obj.mode == 'EDIT':
        in_edit = True
        bm = bmesh.from_edit_mesh(mesh_obj.data)
    else:
        # create temporary bmesh from mesh data to read selection (face select flags are stored)
        bm = bmesh.new()
        bm.from_mesh(mesh_obj.data)

    selected_faces = [f for f in bm.faces if f.select]
    if not selected_faces:
        print('No faces selected on the mesh. Select faces in Edit Mode and run again.')
        if not in_edit:
            bm.free()
        return

    # compute a default bone length based on mesh size
    mesh_diag = mesh_obj.dimensions.length
    default_length = mesh_diag * bone_length_factor if mesh_diag > 0 else 1.0

    arm_obj = ensure_armature()

    # make sure armature is in Object mode to switch to Edit mode next
    bpy.ops.object.mode_set(mode='OBJECT')

    # Select only the armature object and enter Edit mode for bone creation
    bpy.ops.object.select_all(action='DESELECT')
    arm_obj.select_set(True)
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.object.mode_set(mode='EDIT')

    arm_data = arm_obj.data

    # convert world coordinates to armature local
    inv_arm_world = arm_obj.matrix_world.inverted()

    created_bones = []
    for i, face in enumerate(selected_faces, start=1):
        # face centroid in world space
        verts_co = [mesh_obj.matrix_world @ v.co for v in face.verts]
        centroid = Vector((0.0, 0.0, 0.0))
        for vco in verts_co:
            centroid += vco
        centroid /= len(verts_co)
        # face normal in world space
        normal_local = face.normal
        normal_world = (mesh_obj.matrix_world.to_3x3() @ normal_local).normalized()

        # bone head/tail positions in world space
        head_world = centroid
        tail_world = centroid + normal_world * default_length

        # convert to armature local space
        head_local = inv_arm_world @ head_world
        tail_local = inv_arm_world @ tail_world

        bone_name = f"{bone_name_prefix}_{i}"
        eb = arm_data.edit_bones.new(bone_name)
        eb.head = head_local
        eb.tail = tail_local
        # small check to avoid zero-length bones
        if (eb.tail - eb.head).length < 1e-6:
            eb.tail.z += 0.001
        created_bones.append(bone_name)

    # return to Object mode for mesh modifications
    bpy.ops.object.mode_set(mode='OBJECT')

    # Ensure mesh has vertex groups and assign face vertices to corresponding group
    # We will operate on the original mesh data (not bmesh) to assign vertex indices
    mesh = mesh_obj.data
    # Build mapping from face index to its vertex indices
    face_vertex_indices = {}
    # If bm came from edit mode, its face indices correspond to the original mesh
    if in_edit:
        # bmesh keeps same ordering for .index if no re-ordering; ensure indices are synced
        bm.faces.ensure_lookup_table()
        for idx, f in enumerate(bm.faces):
            if f.select:
                face_vertex_indices[idx] = [v.index for v in f.verts]
    else:
        # use mesh polygons
        for poly in mesh.polygons:
            if poly.select:
                face_vertex_indices[poly.index] = list(poly.vertices)

    # Create vertex groups and assign
    bpy.context.view_layer.objects.active = mesh_obj
    mesh_obj.select_set(True)
    for i, bone_name in enumerate(created_bones, start=1):
        # find the corresponding face index for this bone (we enumerated faces earlier)
        # mapping order: selected_faces list preserves order of bm.faces iteration; need to map
        # get the polygon index from selected_faces[i-1]
        f = selected_faces[i-1]
        poly_index = getattr(f, 'index', None)
        if poly_index is None:
            # best-effort fallback: use i-1
            poly_index = list(face_vertex_indices.keys())[i-1]
        v_indices = face_vertex_indices.get(poly_index, [])
        if not v_indices:
            continue
        vg = mesh_obj.vertex_groups.get(bone_name)
        if vg is None:
            vg = mesh_obj.vertex_groups.new(name=bone_name)
        for vi in v_indices:
            try:
                vg.add([vi], 1.0, 'REPLACE')
            except Exception as e:
                print(f'Could not assign vertex {vi} to group {bone_name}: {e}')

    # Add Armature modifier if missing
    mod = None
    for m in mesh_obj.modifiers:
        if m.type == 'ARMATURE':
            mod = m
            break
    if mod is None:
        mod = mesh_obj.modifiers.new(name='Armature', type='ARMATURE')
    mod.object = arm_obj

    # Optionally parent mesh to armature (armature deform)
    # mesh_obj.parent = arm_obj
    # mesh_obj.parent_type = 'OBJECT'

    # cleanup bmesh if created
    if not in_edit:
        bm.free()

    print(f'Created {len(created_bones)} bones and assigned vertex groups.')


if __name__ == '__main__':
    main()
