extends Node

@export_enum(
	"SEQ_SOUND_PLAYER",
	"SEQ_EVENT_CUTSCENE_COLLECT_STAR",
	"SEQ_MENU_TITLE_SCREEN",
	"SEQ_LEVEL_GRASS",
	"SEQ_LEVEL_INSIDE_CASTLE",
	"SEQ_LEVEL_WATER",
	"SEQ_LEVEL_HOT",
	"SEQ_LEVEL_BOSS_KOOPA",
	"SEQ_LEVEL_SNOW",
	"SEQ_LEVEL_SLIDE",
	"SEQ_LEVEL_SPOOKY",
	"SEQ_EVENT_PIRANHA_PLANT",
	"SEQ_LEVEL_UNDERGROUND",
	"SEQ_MENU_STAR_SELECT",
	"SEQ_EVENT_POWERUP",
	"SEQ_EVENT_METAL_CAP",
	"SEQ_EVENT_KOOPA_MESSAGE",
	"SEQ_LEVEL_KOOPA_ROAD",
	"SEQ_EVENT_HIGH_SCORE",
	"SEQ_EVENT_MERRY_GO_ROUND",
	"SEQ_EVENT_RACE",
	"SEQ_EVENT_CUTSCENE_STAR_SPAWN",
	"SEQ_EVENT_BOSS",
	"SEQ_EVENT_CUTSCENE_COLLECT_KEY",
	"SEQ_EVENT_ENDLESS_STAIRS",
	"SEQ_LEVEL_BOSS_KOOPA_FINAL",
	"SEQ_EVENT_CUTSCENE_CREDITS",
	"SEQ_EVENT_SOLVE_PUZZLE",
	"SEQ_EVENT_TOAD_MESSAGE",
	"SEQ_EVENT_PEACH_MESSAGE",
	"SEQ_EVENT_CUTSCENE_INTRO",
	"SEQ_EVENT_CUTSCENE_VICTORY",
	"SEQ_EVENT_CUTSCENE_ENDING",
	"SEQ_MENU_FILE_SELECT",
	"SEQ_EVENT_CUTSCENE_LAKITU",
    "SEQ_COUNT"
)
var music: int = 3

@export var music_index: int = 3
@export var no_music: bool = false

const VANISH_CAP_DURATION := 20.0

var _cap_timer: Timer


func _ready() -> void:
	_cap_timer = Timer.new()
	_cap_timer.one_shot = true
	_cap_timer.wait_time = VANISH_CAP_DURATION
	_cap_timer.timeout.connect(_on_cap_timer_timeout)
	add_child(_cap_timer)


func play_musik(start_cap: LibSM64.MarioFlags = LibSM64.MarioFlags.MARIO_NORMAL_CAP) -> void:
	if no_music:
		return

	var sequences = [
		LibSM64.SEQ_SOUND_PLAYER,
		LibSM64.SEQ_EVENT_CUTSCENE_COLLECT_STAR,
		LibSM64.SEQ_MENU_TITLE_SCREEN,
		LibSM64.SEQ_LEVEL_GRASS,
		LibSM64.SEQ_LEVEL_INSIDE_CASTLE,
		LibSM64.SEQ_LEVEL_WATER,
		LibSM64.SEQ_LEVEL_HOT,
		LibSM64.SEQ_LEVEL_BOSS_KOOPA,
		LibSM64.SEQ_LEVEL_SNOW,
		LibSM64.SEQ_LEVEL_SLIDE,
		LibSM64.SEQ_LEVEL_SPOOKY,
		LibSM64.SEQ_EVENT_PIRANHA_PLANT,
		LibSM64.SEQ_LEVEL_UNDERGROUND,
		LibSM64.SEQ_MENU_STAR_SELECT,
		LibSM64.SEQ_EVENT_POWERUP,
		LibSM64.SEQ_EVENT_METAL_CAP,
		LibSM64.SEQ_EVENT_KOOPA_MESSAGE,
		LibSM64.SEQ_LEVEL_KOOPA_ROAD,
		LibSM64.SEQ_EVENT_HIGH_SCORE,
		LibSM64.SEQ_EVENT_MERRY_GO_ROUND,
		LibSM64.SEQ_EVENT_RACE,
		LibSM64.SEQ_EVENT_CUTSCENE_STAR_SPAWN,
		LibSM64.SEQ_EVENT_BOSS,
		LibSM64.SEQ_EVENT_CUTSCENE_COLLECT_KEY,
		LibSM64.SEQ_EVENT_ENDLESS_STAIRS,
		LibSM64.SEQ_LEVEL_BOSS_KOOPA_FINAL,
		LibSM64.SEQ_EVENT_CUTSCENE_CREDITS,
		LibSM64.SEQ_EVENT_SOLVE_PUZZLE,
		LibSM64.SEQ_EVENT_TOAD_MESSAGE,
		LibSM64.SEQ_EVENT_PEACH_MESSAGE,
		LibSM64.SEQ_EVENT_CUTSCENE_INTRO,
		LibSM64.SEQ_EVENT_CUTSCENE_VICTORY,
		LibSM64.SEQ_EVENT_CUTSCENE_ENDING,
		LibSM64.SEQ_MENU_FILE_SELECT,
		LibSM64.SEQ_EVENT_CUTSCENE_LAKITU
	]

	if (start_cap & LibSM64.MarioFlags.MARIO_METAL_CAP) != 0:
		LibSM64.play_music(
			LibSM64.SEQ_PLAYER_LEVEL,
			LibSM64.SEQ_EVENT_METAL_CAP
		)
		_cap_timer.stop()

	elif (start_cap & LibSM64.MarioFlags.MARIO_WING_CAP) != 0:
		LibSM64.play_music(
			LibSM64.SEQ_PLAYER_LEVEL,
			LibSM64.SEQ_EVENT_POWERUP
		)
		_cap_timer.stop()

	elif (start_cap & LibSM64.MarioFlags.MARIO_VANISH_CAP) != 0:
		LibSM64.play_music(
			LibSM64.SEQ_PLAYER_LEVEL,
			LibSM64.SEQ_EVENT_POWERUP
		)
		_cap_timer.start(VANISH_CAP_DURATION)

	else:
		LibSM64.play_music(
			LibSM64.SEQ_PLAYER_LEVEL,
			sequences[music_index]
		)
		_cap_timer.stop()


func play_level_music() -> void:
	if no_music:
		return

	var sequences = [
		LibSM64.SEQ_SOUND_PLAYER,
		LibSM64.SEQ_EVENT_CUTSCENE_COLLECT_STAR,
		LibSM64.SEQ_MENU_TITLE_SCREEN,
		LibSM64.SEQ_LEVEL_GRASS,
		LibSM64.SEQ_LEVEL_INSIDE_CASTLE,
		LibSM64.SEQ_LEVEL_WATER,
		LibSM64.SEQ_LEVEL_HOT,
		LibSM64.SEQ_LEVEL_BOSS_KOOPA,
		LibSM64.SEQ_LEVEL_SNOW,
		LibSM64.SEQ_LEVEL_SLIDE,
		LibSM64.SEQ_LEVEL_SPOOKY,
		LibSM64.SEQ_EVENT_PIRANHA_PLANT,
		LibSM64.SEQ_LEVEL_UNDERGROUND,
		LibSM64.SEQ_MENU_STAR_SELECT,
		LibSM64.SEQ_EVENT_POWERUP,
		LibSM64.SEQ_EVENT_METAL_CAP,
		LibSM64.SEQ_EVENT_KOOPA_MESSAGE,
		LibSM64.SEQ_LEVEL_KOOPA_ROAD,
		LibSM64.SEQ_EVENT_HIGH_SCORE,
		LibSM64.SEQ_EVENT_MERRY_GO_ROUND,
		LibSM64.SEQ_EVENT_RACE,
		LibSM64.SEQ_EVENT_CUTSCENE_STAR_SPAWN,
		LibSM64.SEQ_EVENT_BOSS,
		LibSM64.SEQ_EVENT_CUTSCENE_COLLECT_KEY,
		LibSM64.SEQ_EVENT_ENDLESS_STAIRS,
		LibSM64.SEQ_LEVEL_BOSS_KOOPA_FINAL,
		LibSM64.SEQ_EVENT_CUTSCENE_CREDITS,
		LibSM64.SEQ_EVENT_SOLVE_PUZZLE,
		LibSM64.SEQ_EVENT_TOAD_MESSAGE,
		LibSM64.SEQ_EVENT_PEACH_MESSAGE,
		LibSM64.SEQ_EVENT_CUTSCENE_INTRO,
		LibSM64.SEQ_EVENT_CUTSCENE_VICTORY,
		LibSM64.SEQ_EVENT_CUTSCENE_ENDING,
		LibSM64.SEQ_MENU_FILE_SELECT,
		LibSM64.SEQ_EVENT_CUTSCENE_LAKITU
	]

	LibSM64.play_music(
		LibSM64.SEQ_PLAYER_LEVEL,
		sequences[music_index]
	)


func _on_cap_timer_timeout() -> void:
	play_level_music()
